-- GENERATED by metrics/generate_views.py from metrics/registry.yaml. Do not edit.
{{ config(alias='games') }}
select g.*, h.full_name as home_team_name, a.full_name as away_team_name
from {{ ref('games') }} g
left join {{ ref('teams') }} h
  on h.team_id = g.home_team_id
 and g.season_start between h.first_season_start and h.last_season_start
left join {{ ref('teams') }} a
  on a.team_id = g.away_team_id
 and g.season_start between a.first_season_start and a.last_season_start
