-- GENERATED by metrics/generate_views.py from metrics/registry.yaml. Do not edit.
{{ config(alias='shots') }}
select s.*, p.name as player_name
from {{ ref('shots') }} s
join {{ ref('players') }} p using (player_id)
