-- GENERATED by metrics/generate_views.py from metrics/registry.yaml. Do not edit.
{{ config(alias='player_titles') }}
select pt.*, p.name as player_name
from {{ ref('player_titles') }} pt
join {{ ref('players') }} p using (player_id)
