-- GENERATED by metrics/generate_views.py from metrics/registry.yaml. Do not edit.
{{ config(alias='awards') }}
select a.*, p.name as player_name
from {{ ref('awards') }} a
join {{ ref('players') }} p using (player_id)
