-- GENERATED by metrics/generate_views.py from metrics/registry.yaml. Do not edit.
{{ config(alias='player_season_stats') }}
-- One row per (player_id, season, season_type). Registry 0.3.0.
with spine as (
select ps.player_id, p.name as player_name, ps.season, ps.season_start, ps.season_type,
       ps.team_count, ps.last_team_id as team_id, t.full_name as team_name,
       ps.gp, ts.gp as team_gp, p.rookie_season = ps.season as is_rookie_season
from {{ ref('player_season') }} ps
join {{ ref('players') }} p using (player_id)
left join {{ ref('team_season') }} ts
  on ts.team_id = ps.last_team_id and ts.season = ps.season and ts.season_type = ps.season_type
left join {{ ref('teams') }} t
  on t.team_id = ps.last_team_id
 and ps.season_start between t.first_season_start and t.last_season_start
),
m0 as (
    -- games_played: GP
    select player_id, season, season_type, sum(gp) as games_played
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m1 as (
    -- games_started: GS
    select player_id, season, season_type, sum(gs) as games_started
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m2 as (
    -- points: PTS
    select player_id, season, season_type, sum(pts) as points
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m3 as (
    -- rebounds: REB
    select player_id, season, season_type, sum(reb) as rebounds
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m4 as (
    -- assists: AST
    select player_id, season, season_type, sum(ast) as assists
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m5 as (
    -- steals: STL
    select player_id, season, season_type, sum(stl) as steals
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m6 as (
    -- blocks: BLK
    select player_id, season, season_type, sum(blk) as blocks
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m7 as (
    -- turnovers: TOV
    select player_id, season, season_type, sum(tov) as turnovers
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m8 as (
    -- minutes: MIN
    select player_id, season, season_type, sum(minutes) as minutes
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m9 as (
    -- field_goals_made: FGM
    select player_id, season, season_type, sum(fgm) as field_goals_made
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m10 as (
    -- threes_made: 3PM
    select player_id, season, season_type, sum(fg3m) as threes_made
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m11 as (
    -- threes_attempted: 3PA
    select player_id, season, season_type, sum(fg3a) as threes_attempted
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m12 as (
    -- free_throws_made: FTM
    select player_id, season, season_type, sum(ftm) as free_throws_made
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m13 as (
    -- points_per_game: PTS / GP
    select player_id, season, season_type, sum(pts) / nullif(sum(gp), 0) as points_per_game
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m14 as (
    -- rebounds_per_game: REB / GP
    select player_id, season, season_type, sum(reb) / nullif(sum(gp), 0) as rebounds_per_game
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m15 as (
    -- assists_per_game: AST / GP
    select player_id, season, season_type, sum(ast) / nullif(sum(gp), 0) as assists_per_game
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m16 as (
    -- steals_per_game: STL / GP
    select player_id, season, season_type, sum(stl) / nullif(sum(gp), 0) as steals_per_game
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m17 as (
    -- blocks_per_game: BLK / GP
    select player_id, season, season_type, sum(blk) / nullif(sum(gp), 0) as blocks_per_game
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m18 as (
    -- minutes_per_game: MIN / GP
    select player_id, season, season_type, sum(minutes) / nullif(sum(gp), 0) as minutes_per_game
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m19 as (
    -- field_goal_pct: FGM / FGA
    select player_id, season, season_type, sum(fgm) / nullif(sum(fga), 0) as field_goal_pct
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m20 as (
    -- three_point_pct: 3PM / 3PA
    select player_id, season, season_type, sum(fg3m) / nullif(sum(fg3a), 0) as three_point_pct
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m21 as (
    -- free_throw_pct: FTM / FTA
    select player_id, season, season_type, sum(ftm) / nullif(sum(fta), 0) as free_throw_pct
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m22 as (
    -- true_shooting_pct: PTS / (2 * (FGA + 0.44 * FTA))
    select player_id, season, season_type, sum(pts) / nullif(2 * (sum(fga) + 0.44 * sum(fta)), 0) as true_shooting_pct
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m23 as (
    -- effective_fg_pct: (FGM + 0.5 * 3PM) / FGA
    select player_id, season, season_type, (sum(fgm) + 0.5 * sum(fg3m)) / nullif(sum(fga), 0) as effective_fg_pct
    from {{ ref('player_season') }}
    group by player_id, season, season_type
),
m24 as (
    -- usage_rate: 100 * ((FGA + 0.44 * FTA + TOV) * (Team MIN / 5)) / (MIN * (Team FGA + 0.44 * Team FTA + Team TOV))
    select player_id, season, season_type, max(usg_pct) as usage_rate
    from {{ ref('player_advanced') }}
    group by player_id, season, season_type
),
m25 as (
    -- triple_doubles: count of games with >= 10 in three of PTS, REB, AST, STL, BLK
    select player_id, season, season_type, count(*) filter (where (coalesce(pts, 0) >= 10)::int + (coalesce(reb, 0) >= 10)::int + (coalesce(ast, 0) >= 10)::int + (coalesce(stl, 0) >= 10)::int + (coalesce(blk, 0) >= 10)::int >= 3) as triple_doubles
    from {{ ref('player_game') }}
    group by player_id, season, season_type
),
m26 as (
    -- double_doubles: count of games with >= 10 in two of PTS, REB, AST, STL, BLK
    select player_id, season, season_type, count(*) filter (where (coalesce(pts, 0) >= 10)::int + (coalesce(reb, 0) >= 10)::int + (coalesce(ast, 0) >= 10)::int + (coalesce(stl, 0) >= 10)::int + (coalesce(blk, 0) >= 10)::int >= 2) as double_doubles
    from {{ ref('player_game') }}
    group by player_id, season, season_type
),
m27 as (
    -- forty_point_games: count of games with PTS >= 40
    select player_id, season, season_type, count(*) filter (where pts >= 40) as forty_point_games
    from {{ ref('player_game') }}
    group by player_id, season, season_type
),
m28 as (
    -- plus_minus: sum of +/- over games
    select player_id, season, season_type, sum(plus_minus) as plus_minus
    from {{ ref('player_game') }}
    group by player_id, season, season_type
),
m29 as (
    -- shot_attempts: count of shots
    select player_id, season, season_type, count(*) as shot_attempts
    from {{ ref('shots') }}
    group by player_id, season, season_type
),
m30 as (
    -- shot_fg_pct: made shots / shots
    select player_id, season, season_type, count(*) filter (where made) / nullif(count(*), 0) as shot_fg_pct
    from {{ ref('shots') }}
    group by player_id, season, season_type
),
m31 as (
    -- restricted_area_fg_pct: made / attempts, zone = Restricted Area
    select player_id, season, season_type, count(*) filter (where made) / nullif(count(*), 0) as restricted_area_fg_pct
    from {{ ref('shots') }}
    where zone = 'Restricted Area'
    group by player_id, season, season_type
),
m32 as (
    -- corner_threes_made: made shots in Left Corner 3 or Right Corner 3
    select player_id, season, season_type, count(*) filter (where made) as corner_threes_made
    from {{ ref('shots') }}
    where zone in ('Left Corner 3', 'Right Corner 3')
    group by player_id, season, season_type
),
m33 as (
    -- step_back_three_pct: made / attempts, 3PT shots with a step-back action type
    select player_id, season, season_type, count(*) filter (where made) / nullif(count(*), 0) as step_back_three_pct
    from {{ ref('shots') }}
    where shot_type = '3PT Field Goal' and action_type ilike 'step back%'
    group by player_id, season, season_type
)
select
    spine.*,
    m0.games_played,
    m1.games_started,
    m2.points,
    m3.rebounds,
    m4.assists,
    m5.steals,
    m6.blocks,
    m7.turnovers,
    m8.minutes,
    m9.field_goals_made,
    m10.threes_made,
    m11.threes_attempted,
    m12.free_throws_made,
    m13.points_per_game,
    m14.rebounds_per_game,
    m15.assists_per_game,
    m16.steals_per_game,
    m17.blocks_per_game,
    m18.minutes_per_game,
    m19.field_goal_pct,
    m20.three_point_pct,
    m21.free_throw_pct,
    m22.true_shooting_pct,
    m23.effective_fg_pct,
    m24.usage_rate,
    m25.triple_doubles,
    m26.double_doubles,
    m27.forty_point_games,
    m28.plus_minus,
    m29.shot_attempts,
    m30.shot_fg_pct,
    m31.restricted_area_fg_pct,
    m32.corner_threes_made,
    m33.step_back_three_pct
from spine
left join m0 on m0.player_id = spine.player_id and m0.season = spine.season and m0.season_type = spine.season_type
left join m1 on m1.player_id = spine.player_id and m1.season = spine.season and m1.season_type = spine.season_type
left join m2 on m2.player_id = spine.player_id and m2.season = spine.season and m2.season_type = spine.season_type
left join m3 on m3.player_id = spine.player_id and m3.season = spine.season and m3.season_type = spine.season_type
left join m4 on m4.player_id = spine.player_id and m4.season = spine.season and m4.season_type = spine.season_type
left join m5 on m5.player_id = spine.player_id and m5.season = spine.season and m5.season_type = spine.season_type
left join m6 on m6.player_id = spine.player_id and m6.season = spine.season and m6.season_type = spine.season_type
left join m7 on m7.player_id = spine.player_id and m7.season = spine.season and m7.season_type = spine.season_type
left join m8 on m8.player_id = spine.player_id and m8.season = spine.season and m8.season_type = spine.season_type
left join m9 on m9.player_id = spine.player_id and m9.season = spine.season and m9.season_type = spine.season_type
left join m10 on m10.player_id = spine.player_id and m10.season = spine.season and m10.season_type = spine.season_type
left join m11 on m11.player_id = spine.player_id and m11.season = spine.season and m11.season_type = spine.season_type
left join m12 on m12.player_id = spine.player_id and m12.season = spine.season and m12.season_type = spine.season_type
left join m13 on m13.player_id = spine.player_id and m13.season = spine.season and m13.season_type = spine.season_type
left join m14 on m14.player_id = spine.player_id and m14.season = spine.season and m14.season_type = spine.season_type
left join m15 on m15.player_id = spine.player_id and m15.season = spine.season and m15.season_type = spine.season_type
left join m16 on m16.player_id = spine.player_id and m16.season = spine.season and m16.season_type = spine.season_type
left join m17 on m17.player_id = spine.player_id and m17.season = spine.season and m17.season_type = spine.season_type
left join m18 on m18.player_id = spine.player_id and m18.season = spine.season and m18.season_type = spine.season_type
left join m19 on m19.player_id = spine.player_id and m19.season = spine.season and m19.season_type = spine.season_type
left join m20 on m20.player_id = spine.player_id and m20.season = spine.season and m20.season_type = spine.season_type
left join m21 on m21.player_id = spine.player_id and m21.season = spine.season and m21.season_type = spine.season_type
left join m22 on m22.player_id = spine.player_id and m22.season = spine.season and m22.season_type = spine.season_type
left join m23 on m23.player_id = spine.player_id and m23.season = spine.season and m23.season_type = spine.season_type
left join m24 on m24.player_id = spine.player_id and m24.season = spine.season and m24.season_type = spine.season_type
left join m25 on m25.player_id = spine.player_id and m25.season = spine.season and m25.season_type = spine.season_type
left join m26 on m26.player_id = spine.player_id and m26.season = spine.season and m26.season_type = spine.season_type
left join m27 on m27.player_id = spine.player_id and m27.season = spine.season and m27.season_type = spine.season_type
left join m28 on m28.player_id = spine.player_id and m28.season = spine.season and m28.season_type = spine.season_type
left join m29 on m29.player_id = spine.player_id and m29.season = spine.season and m29.season_type = spine.season_type
left join m30 on m30.player_id = spine.player_id and m30.season = spine.season and m30.season_type = spine.season_type
left join m31 on m31.player_id = spine.player_id and m31.season = spine.season and m31.season_type = spine.season_type
left join m32 on m32.player_id = spine.player_id and m32.season = spine.season and m32.season_type = spine.season_type
left join m33 on m33.player_id = spine.player_id and m33.season = spine.season and m33.season_type = spine.season_type
