-- GENERATED by metrics/generate_views.py from metrics/registry.yaml. Do not edit.
{{ config(alias='player_stint_stats') }}
-- One row per (player_id, season, season_type, team_id). Registry 0.3.0.
with spine as (
select s.player_id, p.name as player_name, s.season, s.season_start, s.season_type,
       s.team_id, t.full_name as team_name, s.gp, ts.gp as team_gp
from {{ ref('player_season_stint') }} s
join {{ ref('players') }} p using (player_id)
left join {{ ref('team_season') }} ts
  on ts.team_id = s.team_id and ts.season = s.season and ts.season_type = s.season_type
left join {{ ref('teams') }} t
  on t.team_id = s.team_id
 and s.season_start between t.first_season_start and t.last_season_start
),
m0 as (
    -- games_played: GP
    select player_id, season, season_type, team_id, sum(gp) as games_played
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m1 as (
    -- games_started: GS
    select player_id, season, season_type, team_id, sum(gs) as games_started
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m2 as (
    -- points: PTS
    select player_id, season, season_type, team_id, sum(pts) as points
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m3 as (
    -- rebounds: REB
    select player_id, season, season_type, team_id, sum(reb) as rebounds
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m4 as (
    -- assists: AST
    select player_id, season, season_type, team_id, sum(ast) as assists
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m5 as (
    -- steals: STL
    select player_id, season, season_type, team_id, sum(stl) as steals
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m6 as (
    -- blocks: BLK
    select player_id, season, season_type, team_id, sum(blk) as blocks
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m7 as (
    -- turnovers: TOV
    select player_id, season, season_type, team_id, sum(tov) as turnovers
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m8 as (
    -- minutes: MIN
    select player_id, season, season_type, team_id, sum(minutes) as minutes
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m9 as (
    -- field_goals_made: FGM
    select player_id, season, season_type, team_id, sum(fgm) as field_goals_made
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m10 as (
    -- threes_made: 3PM
    select player_id, season, season_type, team_id, sum(fg3m) as threes_made
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m11 as (
    -- threes_attempted: 3PA
    select player_id, season, season_type, team_id, sum(fg3a) as threes_attempted
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m12 as (
    -- free_throws_made: FTM
    select player_id, season, season_type, team_id, sum(ftm) as free_throws_made
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m13 as (
    -- points_per_game: PTS / GP
    select player_id, season, season_type, team_id, sum(pts) / nullif(sum(gp), 0) as points_per_game
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m14 as (
    -- rebounds_per_game: REB / GP
    select player_id, season, season_type, team_id, sum(reb) / nullif(sum(gp), 0) as rebounds_per_game
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m15 as (
    -- assists_per_game: AST / GP
    select player_id, season, season_type, team_id, sum(ast) / nullif(sum(gp), 0) as assists_per_game
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m16 as (
    -- steals_per_game: STL / GP
    select player_id, season, season_type, team_id, sum(stl) / nullif(sum(gp), 0) as steals_per_game
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m17 as (
    -- blocks_per_game: BLK / GP
    select player_id, season, season_type, team_id, sum(blk) / nullif(sum(gp), 0) as blocks_per_game
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m18 as (
    -- minutes_per_game: MIN / GP
    select player_id, season, season_type, team_id, sum(minutes) / nullif(sum(gp), 0) as minutes_per_game
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m19 as (
    -- field_goal_pct: FGM / FGA
    select player_id, season, season_type, team_id, sum(fgm) / nullif(sum(fga), 0) as field_goal_pct
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m20 as (
    -- three_point_pct: 3PM / 3PA
    select player_id, season, season_type, team_id, sum(fg3m) / nullif(sum(fg3a), 0) as three_point_pct
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m21 as (
    -- free_throw_pct: FTM / FTA
    select player_id, season, season_type, team_id, sum(ftm) / nullif(sum(fta), 0) as free_throw_pct
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m22 as (
    -- true_shooting_pct: PTS / (2 * (FGA + 0.44 * FTA))
    select player_id, season, season_type, team_id, sum(pts) / nullif(2 * (sum(fga) + 0.44 * sum(fta)), 0) as true_shooting_pct
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
),
m23 as (
    -- effective_fg_pct: (FGM + 0.5 * 3PM) / FGA
    select player_id, season, season_type, team_id, (sum(fgm) + 0.5 * sum(fg3m)) / nullif(sum(fga), 0) as effective_fg_pct
    from {{ ref('player_season_stint') }}
    group by player_id, season, season_type, team_id
)
select
    spine.*,
    m0.games_played,
    m1.games_started,
    m2.points,
    m3.rebounds,
    m4.assists,
    m5.steals,
    m6.blocks,
    m7.turnovers,
    m8.minutes,
    m9.field_goals_made,
    m10.threes_made,
    m11.threes_attempted,
    m12.free_throws_made,
    m13.points_per_game,
    m14.rebounds_per_game,
    m15.assists_per_game,
    m16.steals_per_game,
    m17.blocks_per_game,
    m18.minutes_per_game,
    m19.field_goal_pct,
    m20.three_point_pct,
    m21.free_throw_pct,
    m22.true_shooting_pct,
    m23.effective_fg_pct
from spine
left join m0 on m0.player_id = spine.player_id and m0.season = spine.season and m0.season_type = spine.season_type and m0.team_id = spine.team_id
left join m1 on m1.player_id = spine.player_id and m1.season = spine.season and m1.season_type = spine.season_type and m1.team_id = spine.team_id
left join m2 on m2.player_id = spine.player_id and m2.season = spine.season and m2.season_type = spine.season_type and m2.team_id = spine.team_id
left join m3 on m3.player_id = spine.player_id and m3.season = spine.season and m3.season_type = spine.season_type and m3.team_id = spine.team_id
left join m4 on m4.player_id = spine.player_id and m4.season = spine.season and m4.season_type = spine.season_type and m4.team_id = spine.team_id
left join m5 on m5.player_id = spine.player_id and m5.season = spine.season and m5.season_type = spine.season_type and m5.team_id = spine.team_id
left join m6 on m6.player_id = spine.player_id and m6.season = spine.season and m6.season_type = spine.season_type and m6.team_id = spine.team_id
left join m7 on m7.player_id = spine.player_id and m7.season = spine.season and m7.season_type = spine.season_type and m7.team_id = spine.team_id
left join m8 on m8.player_id = spine.player_id and m8.season = spine.season and m8.season_type = spine.season_type and m8.team_id = spine.team_id
left join m9 on m9.player_id = spine.player_id and m9.season = spine.season and m9.season_type = spine.season_type and m9.team_id = spine.team_id
left join m10 on m10.player_id = spine.player_id and m10.season = spine.season and m10.season_type = spine.season_type and m10.team_id = spine.team_id
left join m11 on m11.player_id = spine.player_id and m11.season = spine.season and m11.season_type = spine.season_type and m11.team_id = spine.team_id
left join m12 on m12.player_id = spine.player_id and m12.season = spine.season and m12.season_type = spine.season_type and m12.team_id = spine.team_id
left join m13 on m13.player_id = spine.player_id and m13.season = spine.season and m13.season_type = spine.season_type and m13.team_id = spine.team_id
left join m14 on m14.player_id = spine.player_id and m14.season = spine.season and m14.season_type = spine.season_type and m14.team_id = spine.team_id
left join m15 on m15.player_id = spine.player_id and m15.season = spine.season and m15.season_type = spine.season_type and m15.team_id = spine.team_id
left join m16 on m16.player_id = spine.player_id and m16.season = spine.season and m16.season_type = spine.season_type and m16.team_id = spine.team_id
left join m17 on m17.player_id = spine.player_id and m17.season = spine.season and m17.season_type = spine.season_type and m17.team_id = spine.team_id
left join m18 on m18.player_id = spine.player_id and m18.season = spine.season and m18.season_type = spine.season_type and m18.team_id = spine.team_id
left join m19 on m19.player_id = spine.player_id and m19.season = spine.season and m19.season_type = spine.season_type and m19.team_id = spine.team_id
left join m20 on m20.player_id = spine.player_id and m20.season = spine.season and m20.season_type = spine.season_type and m20.team_id = spine.team_id
left join m21 on m21.player_id = spine.player_id and m21.season = spine.season and m21.season_type = spine.season_type and m21.team_id = spine.team_id
left join m22 on m22.player_id = spine.player_id and m22.season = spine.season and m22.season_type = spine.season_type and m22.team_id = spine.team_id
left join m23 on m23.player_id = spine.player_id and m23.season = spine.season and m23.season_type = spine.season_type and m23.team_id = spine.team_id
