-- GENERATED by metrics/generate_views.py from metrics/registry.yaml. Do not edit.
{{ config(alias='player_game_log') }}
-- One row per (player_id, game_id). Registry 0.3.0.
with spine as (
select g.game_id, g.player_id, p.name as player_name, g.team_id, g.season,
       g.season_type, g.game_date, g.matchup, g.wl, g.minutes, g.pts, g.reb, g.ast, g.stl,
       g.blk, g.tov, g.fgm, g.fga, g.fg3m, g.fg3a, g.ftm, g.fta, g.plus_minus
from {{ ref('player_game') }} g
join {{ ref('players') }} p using (player_id)
),
m0 as (
    -- game_points: PTS
    select player_id, game_id, sum(pts) as game_points
    from {{ ref('player_game') }}
    group by player_id, game_id
)
select
    spine.*,
    m0.game_points
from spine
left join m0 on m0.player_id = spine.player_id and m0.game_id = spine.game_id
