-- GENERATED by metrics/generate_views.py from metrics/registry.yaml. Do not edit.
{{ config(alias='league_season_stats') }}
-- One row per (season, season_type). Registry 0.3.0.
with spine as (
select season, any_value(season_start) as season_start, season_type,
       count(distinct team_id) as teams
from {{ ref('team_season') }}
group by season, season_type
),
m0 as (
    -- league_points_per_game: sum of team PTS / sum of team GP
    select season, season_type, sum(pts) / nullif(sum(gp), 0) as league_points_per_game
    from {{ ref('team_season') }}
    group by season, season_type
),
m1 as (
    -- league_three_point_attempt_rate: sum of 3PA / sum of FGA
    select season, season_type, sum(fg3a) / nullif(sum(fga), 0) as league_three_point_attempt_rate
    from {{ ref('team_season') }}
    group by season, season_type
)
select
    spine.*,
    m0.league_points_per_game,
    m1.league_three_point_attempt_rate
from spine
left join m0 on m0.season = spine.season and m0.season_type = spine.season_type
left join m1 on m1.season = spine.season and m1.season_type = spine.season_type
