-- GENERATED by metrics/generate_views.py from metrics/registry.yaml. Do not edit.
{{ config(alias='records') }}
select r.*, p.name as player_name
from {{ ref('records') }} r
left join {{ ref('players') }} p using (player_id)
