-- GENERATED by metrics/generate_views.py from metrics/registry.yaml. Do not edit.
{{ config(alias='team_all_time_stats') }}
-- One row per (franchise_id, season_type). Registry 0.3.0.
with spine as (
select f.franchise_id, f.current_name as team_name, st.season_type
from {{ ref('franchises') }} f
cross join (select distinct season_type from {{ ref('team_season') }}) st
),
m0 as (
    -- wins: W
    select franchise_id, season_type, sum(wins) as wins
    from {{ ref('team_season') }}
    group by franchise_id, season_type
),
m1 as (
    -- losses: L
    select franchise_id, season_type, sum(losses) as losses
    from {{ ref('team_season') }}
    group by franchise_id, season_type
),
m2 as (
    -- win_pct: W / GP
    select franchise_id, season_type, sum(wins) / nullif(sum(gp), 0) as win_pct
    from {{ ref('team_season') }}
    group by franchise_id, season_type
),
m3 as (
    -- team_points_per_game: Team PTS / GP
    select franchise_id, season_type, sum(pts) / nullif(sum(gp), 0) as team_points_per_game
    from {{ ref('team_season') }}
    group by franchise_id, season_type
),
m4 as (
    -- opponent_points_per_game: Opp PTS / GP
    select franchise_id, season_type, sum(opp_pts) / nullif(sum(gp), 0) as opponent_points_per_game
    from {{ ref('team_season') }}
    group by franchise_id, season_type
),
m5 as (
    -- championships: count of seasons as league champion
    select franchise_id, count(*) as championships
    from {{ ref('team_titles') }}
    group by franchise_id
)
select
    spine.*,
    m0.wins,
    m1.losses,
    m2.win_pct,
    m3.team_points_per_game,
    m4.opponent_points_per_game,
    m5.championships
from spine
left join m0 on m0.franchise_id = spine.franchise_id and m0.season_type = spine.season_type
left join m1 on m1.franchise_id = spine.franchise_id and m1.season_type = spine.season_type
left join m2 on m2.franchise_id = spine.franchise_id and m2.season_type = spine.season_type
left join m3 on m3.franchise_id = spine.franchise_id and m3.season_type = spine.season_type
left join m4 on m4.franchise_id = spine.franchise_id and m4.season_type = spine.season_type
left join m5 on m5.franchise_id = spine.franchise_id
