-- GENERATED by metrics/generate_views.py from metrics/registry.yaml. Do not edit.
{{ config(alias='team_season_stats') }}
-- One row per (team_id, season, season_type). Registry 0.3.0.
with spine as (
select ts.team_id, t.full_name as team_name, ts.season, ts.season_start,
       ts.season_type, ts.conference, ts.division, ts.conference_rank, ts.league_rank,
       ts.gp, ts.neutral_games, ts.road_wins, ts.road_losses
from {{ ref('team_season') }} ts
left join {{ ref('teams') }} t
  on t.team_id = ts.team_id
 and ts.season_start between t.first_season_start and t.last_season_start
),
m0 as (
    -- wins: W
    select team_id, season, season_type, sum(wins) as wins
    from {{ ref('team_season') }}
    group by team_id, season, season_type
),
m1 as (
    -- losses: L
    select team_id, season, season_type, sum(losses) as losses
    from {{ ref('team_season') }}
    group by team_id, season, season_type
),
m2 as (
    -- win_pct: W / GP
    select team_id, season, season_type, sum(wins) / nullif(sum(gp), 0) as win_pct
    from {{ ref('team_season') }}
    group by team_id, season, season_type
),
m3 as (
    -- team_points_per_game: Team PTS / GP
    select team_id, season, season_type, sum(pts) / nullif(sum(gp), 0) as team_points_per_game
    from {{ ref('team_season') }}
    group by team_id, season, season_type
),
m4 as (
    -- opponent_points_per_game: Opp PTS / GP
    select team_id, season, season_type, sum(opp_pts) / nullif(sum(gp), 0) as opponent_points_per_game
    from {{ ref('team_season') }}
    group by team_id, season, season_type
),
m5 as (
    -- offensive_rating: 100 * PTS / possessions
    select team_id, season, season_type, max(off_rating) as offensive_rating
    from {{ ref('team_season') }}
    group by team_id, season, season_type
),
m6 as (
    -- defensive_rating: 100 * Opp PTS / possessions
    select team_id, season, season_type, max(def_rating) as defensive_rating
    from {{ ref('team_season') }}
    group by team_id, season, season_type
),
m7 as (
    -- net_rating: ORtg - DRtg
    select team_id, season, season_type, max(net_rating) as net_rating
    from {{ ref('team_season') }}
    group by team_id, season, season_type
),
m8 as (
    -- pace: 48 * possessions / (team minutes / 5)
    select team_id, season, season_type, max(pace) as pace
    from {{ ref('team_season') }}
    group by team_id, season, season_type
),
m9 as (
    -- home_wins: home W
    select team_id, season, season_type, sum(home_wins) as home_wins
    from {{ ref('team_season') }}
    group by team_id, season, season_type
),
m10 as (
    -- home_losses: home L
    select team_id, season, season_type, sum(home_losses) as home_losses
    from {{ ref('team_season') }}
    group by team_id, season, season_type
),
m11 as (
    -- road_wins: road W
    select team_id, season, season_type, sum(road_wins) as road_wins
    from {{ ref('team_season') }}
    group by team_id, season, season_type
),
m12 as (
    -- road_losses: road L
    select team_id, season, season_type, sum(road_losses) as road_losses
    from {{ ref('team_season') }}
    group by team_id, season, season_type
)
select
    spine.*,
    m0.wins,
    m1.losses,
    m2.win_pct,
    m3.team_points_per_game,
    m4.opponent_points_per_game,
    m5.offensive_rating,
    m6.defensive_rating,
    m7.net_rating,
    m8.pace,
    m9.home_wins,
    m10.home_losses,
    m11.road_wins,
    m12.road_losses
from spine
left join m0 on m0.team_id = spine.team_id and m0.season = spine.season and m0.season_type = spine.season_type
left join m1 on m1.team_id = spine.team_id and m1.season = spine.season and m1.season_type = spine.season_type
left join m2 on m2.team_id = spine.team_id and m2.season = spine.season and m2.season_type = spine.season_type
left join m3 on m3.team_id = spine.team_id and m3.season = spine.season and m3.season_type = spine.season_type
left join m4 on m4.team_id = spine.team_id and m4.season = spine.season and m4.season_type = spine.season_type
left join m5 on m5.team_id = spine.team_id and m5.season = spine.season and m5.season_type = spine.season_type
left join m6 on m6.team_id = spine.team_id and m6.season = spine.season and m6.season_type = spine.season_type
left join m7 on m7.team_id = spine.team_id and m7.season = spine.season and m7.season_type = spine.season_type
left join m8 on m8.team_id = spine.team_id and m8.season = spine.season and m8.season_type = spine.season_type
left join m9 on m9.team_id = spine.team_id and m9.season = spine.season and m9.season_type = spine.season_type
left join m10 on m10.team_id = spine.team_id and m10.season = spine.season and m10.season_type = spine.season_type
left join m11 on m11.team_id = spine.team_id and m11.season = spine.season and m11.season_type = spine.season_type
left join m12 on m12.team_id = spine.team_id and m12.season = spine.season and m12.season_type = spine.season_type
