"""Generate the semantic layer from the metric registry (task 1.23).

Usage: ``uv run python -m metrics.generate_views`` (also run by every snapshot build)

Writes one dbt view per file into ``transform/models/semantic/`` (files are ``sem_<view>.sql``
with a dbt alias, because model names must be unique and marts already use names such as
``games``; the views are ``semantic.<view>``) and the view allowlist the SQL
fallback enforces (``transform/semantic_allowlist.txt``). Metric columns come only from
``metrics/registry.yaml``: each metric's aggregate ``sql`` (after its optional ``filter``) is
evaluated over its base rows, grouped by the keys of each grain the metric allows. Adding a metric
is one YAML entry; its column appears in every view for its grains.

The generated files are committed. ``tests/test_semantic_views.py`` fails if they drift from the
registry.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

from metrics.schema import Base, Grain, Metric, Registry, load

REPO = Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "transform" / "models" / "semantic"
ALLOWLIST = REPO / "transform" / "semantic_allowlist.txt"
HEADER = "-- GENERATED by metrics/generate_views.py from metrics/registry.yaml. Do not edit.\n"


@dataclass(frozen=True)
class Source:
    relation: str  # dbt ref expression
    keys: tuple[str, ...]


# Where a metric's base rows come from at a given grain, and the grain's key columns.
SOURCES: dict[tuple[Base, Grain], Source] = {
    (Base.player_season, Grain.player_season): Source(
        "ref('player_season')", ("player_id", "season", "season_type")
    ),
    (Base.player_season, Grain.player_career): Source(
        "ref('player_season')", ("player_id", "season_type")
    ),
    (Base.player_season, Grain.player_stint): Source(
        "ref('player_season_stint')", ("player_id", "season", "season_type", "team_id")
    ),
    (Base.player_game, Grain.player_season): Source(
        "ref('player_game')", ("player_id", "season", "season_type")
    ),
    (Base.player_game, Grain.player_career): Source(
        "ref('player_game')", ("player_id", "season_type")
    ),
    (Base.player_game, Grain.player_game): Source("ref('player_game')", ("player_id", "game_id")),
    (Base.player_advanced, Grain.player_season): Source(
        "ref('player_advanced')", ("player_id", "season", "season_type")
    ),
    (Base.shots, Grain.player_season): Source(
        "ref('shots')", ("player_id", "season", "season_type")
    ),
    (Base.shots, Grain.player_career): Source("ref('shots')", ("player_id", "season_type")),
    (Base.awards, Grain.player_career): Source("ref('awards')", ("player_id",)),
    (Base.player_titles, Grain.player_career): Source("ref('player_titles')", ("player_id",)),
    (Base.team_season, Grain.team_season): Source(
        "ref('team_season')", ("team_id", "season", "season_type")
    ),
    (Base.team_season, Grain.team_all_time): Source(
        "ref('team_season')", ("franchise_id", "season_type")
    ),
    (Base.team_titles, Grain.team_all_time): Source("ref('team_titles')", ("franchise_id",)),
    (Base.league_season, Grain.league_season): Source(
        "ref('team_season')", ("season", "season_type")
    ),
}

# The spine of each metric view: one row per key, plus descriptive columns.
SPINES: dict[Grain, tuple[str, str, tuple[str, ...]]] = {
    Grain.player_season: (
        "player_season_stats",
        """select ps.player_id, p.name as player_name, ps.season, ps.season_start, ps.season_type,
       ps.team_count, ps.last_team_id as team_id, t.full_name as team_name,
       ps.gp, ts.gp as team_gp, p.rookie_season = ps.season as is_rookie_season
from {{ ref('player_season') }} ps
join {{ ref('players') }} p using (player_id)
left join {{ ref('team_season') }} ts
  on ts.team_id = ps.last_team_id and ts.season = ps.season and ts.season_type = ps.season_type
left join {{ ref('teams') }} t
  on t.team_id = ps.last_team_id
 and ps.season_start between t.first_season_start and t.last_season_start""",
        ("player_id", "season", "season_type"),
    ),
    Grain.player_career: (
        "player_career_stats",
        """select ps.player_id, p.name as player_name, ps.season_type,
       count(*) as seasons, min(ps.season) as first_season, max(ps.season) as last_season
from {{ ref('player_season') }} ps
join {{ ref('players') }} p using (player_id)
group by all""",
        ("player_id", "season_type"),
    ),
    Grain.player_stint: (
        "player_stint_stats",
        """select s.player_id, p.name as player_name, s.season, s.season_start, s.season_type,
       s.team_id, t.full_name as team_name, s.gp, ts.gp as team_gp
from {{ ref('player_season_stint') }} s
join {{ ref('players') }} p using (player_id)
left join {{ ref('team_season') }} ts
  on ts.team_id = s.team_id and ts.season = s.season and ts.season_type = s.season_type
left join {{ ref('teams') }} t
  on t.team_id = s.team_id
 and s.season_start between t.first_season_start and t.last_season_start""",
        ("player_id", "season", "season_type", "team_id"),
    ),
    Grain.player_game: (
        "player_game_log",
        """select g.game_id, g.player_id, p.name as player_name, g.team_id, g.season,
       g.season_type, g.game_date, g.matchup, g.wl, g.minutes, g.pts, g.reb, g.ast, g.stl,
       g.blk, g.tov, g.fgm, g.fga, g.fg3m, g.fg3a, g.ftm, g.fta, g.plus_minus
from {{ ref('player_game') }} g
join {{ ref('players') }} p using (player_id)""",
        ("player_id", "game_id"),
    ),
    Grain.team_season: (
        "team_season_stats",
        """select ts.team_id, t.full_name as team_name, ts.season, ts.season_start,
       ts.season_type, ts.conference, ts.division, ts.conference_rank, ts.league_rank,
       ts.gp, ts.neutral_games, ts.road_wins, ts.road_losses
from {{ ref('team_season') }} ts
left join {{ ref('teams') }} t
  on t.team_id = ts.team_id
 and ts.season_start between t.first_season_start and t.last_season_start""",
        ("team_id", "season", "season_type"),
    ),
    Grain.team_all_time: (
        "team_all_time_stats",
        """select f.franchise_id, f.current_name as team_name, st.season_type
from {{ ref('franchises') }} f
cross join (select distinct season_type from {{ ref('team_season') }}) st""",
        ("franchise_id", "season_type"),
    ),
    Grain.league_season: (
        "league_season_stats",
        """select season, any_value(season_start) as season_start, season_type,
       count(distinct team_id) as teams
from {{ ref('team_season') }}
group by season, season_type""",
        ("season", "season_type"),
    ),
}

# Plain views over marts that need no metric columns.
PASSTHROUGH: dict[str, str] = {
    "players": "select * from {{ ref('players') }}",
    "player_aliases": "select * from {{ ref('player_aliases') }}",
    "team_aliases": "select * from {{ ref('team_aliases') }}",
    "teams": "select * from {{ ref('teams') }}",
    "franchises": "select * from {{ ref('franchises') }}",
    "stat_availability": "select * from {{ ref('stat_availability') }}",
    "records": """select r.*, p.name as player_name
from {{ ref('records') }} r
left join {{ ref('players') }} p using (player_id)""",
    "awards": """select a.*, p.name as player_name
from {{ ref('awards') }} a
join {{ ref('players') }} p using (player_id)""",
    "team_titles": "select * from {{ ref('team_titles') }}",
    "player_titles": """select pt.*, p.name as player_name
from {{ ref('player_titles') }} pt
join {{ ref('players') }} p using (player_id)""",
    "games": """select g.*, h.full_name as home_team_name, a.full_name as away_team_name
from {{ ref('games') }} g
left join {{ ref('teams') }} h
  on h.team_id = g.home_team_id
 and g.season_start between h.first_season_start and h.last_season_start
left join {{ ref('teams') }} a
  on a.team_id = g.away_team_id
 and g.season_start between a.first_season_start and a.last_season_start""",
    "shots": """select s.*, p.name as player_name
from {{ ref('shots') }} s
join {{ ref('players') }} p using (player_id)""",
}


def metric_cte(m: Metric, src: Source, idx: int) -> str:
    keys = ", ".join(src.keys)
    where = f"\n    where {m.filter}" if m.filter else ""
    return (
        f"m{idx} as (\n    -- {m.name}: {m.formula}\n"
        f"    select {keys}, {m.sql} as {m.name}\n"
        f"    from {{{{ {src.relation} }}}}{where}\n    group by {keys}\n)"
    )


def metric_view(reg: Registry, grain: Grain) -> str:
    _, spine_sql, keys = SPINES[grain]
    metrics = [m for m in reg.metrics if grain in m.grains]
    ctes = [f"spine as (\n{spine_sql}\n)"]
    joins = []
    cols = []
    for i, m in enumerate(metrics):
        src = SOURCES.get((m.base, grain))
        if src is None:
            raise ValueError(f"{m.name}: no source for base {m.base} at grain {grain}")
        ctes.append(metric_cte(m, src, i))
        # Metrics whose base has fewer keys (e.g. awards per player) join on the shared keys.
        on = " and ".join(f"m{i}.{k} = spine.{k}" for k in src.keys if k in keys)
        if grain == Grain.player_career and src.keys == ("player_id",):
            on += " and spine.season_type = 'Regular Season'"
        joins.append(f"left join m{i} on {on}")
        cols.append(f"    m{i}.{m.name}")
    body = (
        f"{HEADER}-- One row per ({', '.join(keys)}). Registry {reg.version}.\n"
        f"with {',\n'.join(ctes)}\n"
        f"select\n    spine.*,\n{',\n'.join(cols)}\nfrom spine\n" + "\n".join(joins) + "\n"
    )
    return body


def registry_info(reg: Registry) -> str:
    return (
        f"{HEADER}select '{reg.version}' as registry_version, {len(reg.metrics)} as metric_count\n"
    )


def _with_alias(view: str, sql: str) -> str:
    return sql.replace(HEADER, f"{HEADER}{{{{ config(alias='{view}') }}}}\n", 1)


def render(reg: Registry) -> dict[str, str]:
    """Map of file name (``sem_<view>.sql``) to SQL."""
    views: dict[str, str] = {}
    for view, sql in PASSTHROUGH.items():
        views[view] = f"{HEADER}{sql}\n"
    for grain in SPINES:
        views[SPINES[grain][0]] = metric_view(reg, grain)
    views["registry_info"] = registry_info(reg)
    return {f"sem_{v}.sql": _with_alias(v, sql) for v, sql in views.items()}


def allowlist(files: Iterable[str]) -> str:
    names = sorted(f.removesuffix(".sql").removeprefix("sem_") for f in files)
    return (
        "# Semantic-layer views the SQL fallback may read (task 1.23 -> 3.16). Generated.\n"
        + "\n".join(f"semantic.{n}" for n in names)
        + "\n"
    )


def write(reg: Registry | None = None, out_dir: Path = OUT_DIR, allow: Path = ALLOWLIST) -> None:
    reg = reg or load()
    files = render(reg)
    out_dir.mkdir(parents=True, exist_ok=True)
    for old in out_dir.glob("*.sql"):
        if old.name not in files:
            old.unlink()
    for fname, sql in files.items():
        (out_dir / fname).write_text(sql)
    allow.write_text(allowlist(files))


if __name__ == "__main__":
    write()
